// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class AsignacionTrabajo
{
    public int AsignacionTrabajosPk { get; set; }

    public int TrabajoPk { get; set; }

    public int UsuarioCreadorPk { get; set; }

    public int UsuarioOperarioPk { get; set; }

    public int EstadoAsignacionTrabajoPk { get; set; }

    public DateTime? FechaAsignada { get; set; }

    public DateTime? FechaEjecucion { get; set; }

    public bool Datos { get; set; }

    public bool Firma { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Usuario UsuarioCreadorPkNavigation { get; set; }

    public virtual Usuario UsuarioOperarioPkNavigation { get; set; }
}