// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Cliente
{
    public int ClientePk { get; set; }

    public int TipoClientePk { get; set; }

    public int? DireccionPk { get; set; }

    public string Nombre { get; set; }

    public string DocIdentidad { get; set; }

    public string Telefono { get; set; }

    public string Movil { get; set; }

    public string Correo { get; set; }

    public string Ncuenta { get; set; }

    public string NombreAdministracion { get; set; }

    public string Notas { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Direccion DireccionPkNavigation { get; set; }

    public virtual ICollection<NotasCliente> NotasClientes { get; set; } = new List<NotasCliente>();

    public virtual ICollection<Obra> Obras { get; set; } = new List<Obra>();

    public virtual TiposCliente TipoClientePkNavigation { get; set; }
}