// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class DescansosTrabajo
{
    public int DescansosTrabajosPk { get; set; }

    public int TrabajoPk { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public string Descripcion { get; set; }

    public virtual Trabajo TrabajoPkNavigation { get; set; }
}