// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Direccion
{
    public int DireccionPk { get; set; }

    public string TipoVia { get; set; }

    public string NombreVia { get; set; }

    public string Numero { get; set; }

    public string RestoVia { get; set; }

    public string CodigoPostal { get; set; }

    public string CodigoPostalInternacional { get; set; }

    public string Poblacion { get; set; }

    public string PoblacionInternacional { get; set; }

    public string CodigoProvincia { get; set; }

    public string Provincia { get; set; }

    public string CodigoPais { get; set; }

    public string Pais { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual ICollection<Obra> Obras { get; set; } = new List<Obra>();

    public virtual ICollection<OrderDato> OrderDatos { get; set; } = new List<OrderDato>();

    public virtual ICollection<Persona> Personas { get; set; } = new List<Persona>();
}