// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Obra
{
    public int ObraPk { get; set; }

    public int ClientePk { get; set; }

    public int DireccionPk { get; set; }

    public int EstadoObraPk { get; set; }

    public int UgestorPk { get; set; }

    public string Nombre { get; set; }

    public DateTime? FechaAsignada { get; set; }

    public DateTime? FechaFinAsignada { get; set; }

    public DateTime? Fecha { get; set; }

    public DateTime? FechaFin { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Cliente ClientePkNavigation { get; set; }

    public virtual Direccion DireccionPkNavigation { get; set; }

    public virtual EstadoObra EstadoObraPkNavigation { get; set; }

    public virtual ICollection<NotasObra> NotasObras { get; set; } = new List<NotasObra>();

    public virtual ICollection<Trabajo> Trabajos { get; set; } = new List<Trabajo>();

    public virtual Usuario UgestorPkNavigation { get; set; }
}