// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class OrderDato
{
    public int OrderDatosPk { get; set; }

    public int OrderPk { get; set; }

    public int SiniestroPk { get; set; }

    public int GremioPk { get; set; }

    public DateTime? OrderDate { get; set; }

    public DateTime? OrderDateClose { get; set; }

    public string RamoPoliza { get; set; }

    public bool Fraude { get; set; }

    public string Observaciones { get; set; }

    public int DireccionPk { get; set; }

    public int? PafectadaPk { get; set; }

    public int? PinterlocutorPk { get; set; }

    public int? PtramitadorPk { get; set; }

    public int? PcontactoPk { get; set; }

    public int? PaseguradoPk { get; set; }

    public int? PtomadorPk { get; set; }

    public int? PagentePolizaPk { get; set; }

    public int? PprofesionalPk { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Direccion DireccionPkNavigation { get; set; }

    public virtual Gremio GremioPkNavigation { get; set; }

    public virtual Order OrderPkNavigation { get; set; }

    public virtual Persona PafectadaPkNavigation { get; set; }

    public virtual Persona PagentePolizaPkNavigation { get; set; }

    public virtual Persona PaseguradoPkNavigation { get; set; }

    public virtual Persona PcontactoPkNavigation { get; set; }

    public virtual Persona PinterlocutorPkNavigation { get; set; }

    public virtual Persona PprofesionalPkNavigation { get; set; }

    public virtual Persona PtomadorPkNavigation { get; set; }

    public virtual Persona PtramitadorPkNavigation { get; set; }

    public virtual Siniestro SiniestroPkNavigation { get; set; }
}