// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Order
{
    public int OrderPk { get; set; }

    public string IdOrder { get; set; }

    public string Company { get; set; }

    public string IdClaim { get; set; }

    public DateTime? OperationDate { get; set; }

    public string OperationType { get; set; }

    public string OperationDescription { get; set; }

    public string IdProfesional { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<Dialog> Dialogs { get; set; } = new List<Dialog>();

    public virtual ICollection<OrderDato> OrderDatos { get; set; } = new List<OrderDato>();
}