// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Siniestro
{
    public int SiniestroPk { get; set; }

    public int DetallesSiniestroPk { get; set; }

    public int TipoIntervencionPk { get; set; }

    public DateTime? FechaIntervencion { get; set; }

    public string OrderCompany { get; set; }

    public string Estado { get; set; }

    public string TipoProfesional { get; set; }

    public bool Urgente { get; set; }

    public bool Fraude { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual DetallesSiniestro DetallesSiniestroPkNavigation { get; set; }

    public virtual ICollection<NotasSiniestro> NotasSiniestros { get; set; } = new List<NotasSiniestro>();

    public virtual ICollection<OrderDato> OrderDatos { get; set; } = new List<OrderDato>();

    public virtual TiposIntervencione TipoIntervencionPkNavigation { get; set; }

    public virtual ICollection<Trabajo> Trabajos { get; set; } = new List<Trabajo>();
}