// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Telefono
{
    public int TelefonoPk { get; set; }

    public string Prefijo { get; set; }

    public string NumeroTelefono { get; set; }

    public string HorarioPreferenciaLlamada { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<Persona> PersonaNumeroTelefono2PkNavigations { get; set; } = new List<Persona>();

    public virtual ICollection<Persona> PersonaNumeroTelefonoPkNavigations { get; set; } = new List<Persona>();
}