// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Trabajo
{
    public int TrabajoPk { get; set; }

    public int? ObraPk { get; set; }

    public int? SiniestroPk { get; set; }

    public int UgestorPk { get; set; }

    public int UoperarioPk { get; set; }

    public int EstadoTrabajoPk { get; set; }

    public DateTime FechaAsignada { get; set; }

    public DateTime? FechaEjecucion { get; set; }

    public string Descripcion { get; set; }

    public bool Fotos { get; set; }

    public bool HayFirma { get; set; }

    public string Dnifirma { get; set; }

    public bool HayDaños { get; set; }

    public string Daños { get; set; }

    public bool Urgencia { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual EstadosTrabajo EstadoTrabajoPkNavigation { get; set; }

    public virtual ICollection<NotasTrabajo> NotasTrabajos { get; set; } = new List<NotasTrabajo>();

    public virtual Obra ObraPkNavigation { get; set; }

    public virtual Siniestro SiniestroPkNavigation { get; set; }

    public virtual Usuario UgestorPkNavigation { get; set; }

    public virtual Usuario UoperarioPkNavigation { get; set; }
}