// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Trabajo
{
    public int TrabajoPk { get; set; }

    public int? ObraPk { get; set; }

    public int? SiniestroPk { get; set; }

    public int UgestorPk { get; set; }

    public int UasignadoPk { get; set; }

    public int EstadoTrabajoPk { get; set; }

    public DateTime FechaAsignada { get; set; }

    public DateTime FechaFinAsignada { get; set; }

    public DateTime? FechaEjecucion { get; set; }

    public DateTime? FechaFinEjecucion { get; set; }

    public string TiempoTranscurridoDescansos { get; set; }

    public string TiempoTransacurridoTrabajo { get; set; }

    public bool Urgencia { get; set; }

    public string DescripcionAdministrador { get; set; }

    public bool Fotos { get; set; }

    public string DescripcionTrabajo { get; set; }

    public bool HayFirma { get; set; }

    public string NombreAseguradoParteGeneralli { get; set; }

    public string Dnifirma { get; set; }

    public string DescripcionParteGeneralli { get; set; }

    public bool HayDaños { get; set; }

    public string Daños { get; set; }

    public string Observaciones { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<DescansosTrabajo> DescansosTrabajos { get; set; } = new List<DescansosTrabajo>();

    public virtual EstadosTrabajo EstadoTrabajoPkNavigation { get; set; }

    public virtual ICollection<NotasTrabajo> NotasTrabajos { get; set; } = new List<NotasTrabajo>();

    public virtual Obra ObraPkNavigation { get; set; }

    public virtual Siniestro SiniestroPkNavigation { get; set; }

    public virtual Usuario UasignadoPkNavigation { get; set; }

    public virtual ICollection<UbicacionesTrabajo> UbicacionesTrabajos { get; set; } = new List<UbicacionesTrabajo>();

    public virtual Usuario UgestorPkNavigation { get; set; }
}