// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class UbicacionesTrabajo
{
    public int UbicacionTrabajoPk { get; set; }

    public int? TrabajoPk { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Accuracy { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Trabajo TrabajoPkNavigation { get; set; }
}