// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Regal_Plataforma.Models.BDD;

public partial class Usuario
{
    public int UsuarioPk { get; set; }

    public int? RolPk { get; set; }

    public string Usuario1 { get; set; }

    public string Contrasena { get; set; }

    public string Nombre { get; set; }

    public string Apellidos { get; set; }

    public bool Externo { get; set; }

    public bool Operario { get; set; }

    public bool Gestor { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<AsignacionTrabajo> AsignacionTrabajoUsuarioCreadorPkNavigations { get; set; } = new List<AsignacionTrabajo>();

    public virtual ICollection<AsignacionTrabajo> AsignacionTrabajoUsuarioOperarioPkNavigations { get; set; } = new List<AsignacionTrabajo>();

    public virtual ICollection<NotasCliente> NotasClientes { get; set; } = new List<NotasCliente>();

    public virtual ICollection<NotasObra> NotasObras { get; set; } = new List<NotasObra>();

    public virtual ICollection<NotasSiniestro> NotasSiniestros { get; set; } = new List<NotasSiniestro>();

    public virtual ICollection<NotasTrabajo> NotasTrabajos { get; set; } = new List<NotasTrabajo>();

    public virtual ICollection<NotasUsuario> NotasUsuarioUcreadorPkNavigations { get; set; } = new List<NotasUsuario>();

    public virtual ICollection<NotasUsuario> NotasUsuarioUsuarioPkNavigations { get; set; } = new List<NotasUsuario>();

    public virtual ICollection<Obra> Obras { get; set; } = new List<Obra>();

    public virtual Role RolPkNavigation { get; set; }

    public virtual ICollection<Trabajo> TrabajoUgestorPkNavigations { get; set; } = new List<Trabajo>();

    public virtual ICollection<Trabajo> TrabajoUoperarioPkNavigations { get; set; } = new List<Trabajo>();
}